title: Jennifer M. Traver
theme: just-the-docs

url: https://jmtraver.github.io/

callouts:
  warning:
    title: Warning
    color: red
callouts:
  note:
    title: Note
    color: purple
enable_copy_code_button: true
