title: Jennifer M. Traver
theme: just-the-docs

url: https://jmtraver.github.io/

callouts:
  warning:
    title: Warning
    color: red
    
markdown: JdvpCodeTabsCommonMark

enable_copy_code_button: true
